
name: NodeJS Build & Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Node.js 16.x
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
          cache: 'npm'
      - name: Install VS Code linux dependencies
        run: sudo apt install xvfb -y
      - name: Install app and dependencies
        run: npm install
      - name: Pre-test activities
        run: npm run pretest
      - name: Run the tests
        run: xvfb-run -a npm test
