
name: CI Tests

on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "main"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install Node
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
      - name: Install Linux deps
        run: sudo apt install xvfb -y
      - name: Install all
        run: npm run install:all
      - name: Build everything
        run: npm run build:all
      - name: Run unit tests
        run: npm run test:unit
      - name: Run integration tests
        run: xvfb-run -a npm test

